<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TDLib" Version="1.8.63" />
    <PackageReference Include="tdlib.native" Version="1.8.63" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MySpider.Core\MySpider.Core.csproj" />
  </ItemGroup>

</Project>
